### ISSUE TITLE
Canto-daemon won't start

### ISSUE THREAD

**Issue by dmaglio** [themoken/canto-next#26] opened 2015-12-21 10:36 UTC
I have installed canto from git and daemon cannot start. i attach the daemon-log
[daemon-log.txt](https://github.com/themoken/canto-next/files/68351/daemon-log.txt)

**Comment by themoken** [comment] 2015-12-21 16:21
Hmm. I've never seen tempfile.mkstemp fail... even if the two variable arguments are `None` it should work (and create /tmp/feeds).

I put up a quick one-liner that changes the None to "", so see if git works, but if it does I think this is a python bug.

**Comment by themoken** [comment] 2016-01-20 16:15
Closing this since I can't reproduce and you haven't got back to me in a month on whether git fixes it. If it crops up again, feel free to reopen.

**Closed by themoken** 2016-01-20 16:15 UTC
