### ISSUE TITLE
user password for Jira RSS feed

### ISSUE THREAD

**Issue by kjellgren** [themoken/canto-next#18] opened 2014-12-24 16:00 UTC
Configure user and password for url (Jira2) do not work for me. "<unknown>:2:942: mismatched tag". User and password as args in url (Jira1) works fine

https://confluence.atlassian.com/display/JIRA/Receiving+Search+Results+as+an+RSS+Feed

```
{
    "CantoCurses": {
        "browser": {
            "path": "lynx"
        }
    },
    "defaults": {
        "global_transform": "None",
        "keep_time": 86400,
        "keep_unread": false,
        "rate": 10
    },
    "feeds": [
        {
            "name": "Jira1",
            "url": "https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic&os_username=benny&os_password=secret"
        },
        {
            "name": "Jira2",
            "password": "secret",
            "url": "https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic",
            "user": "benny"
        }
    ]
}

16:01:56 : CANTO-DAEMON -> canto-daemon 0.9.0
16:01:56 : CANTO-DAEMON -> verbosity = 1
16:01:56 : CANTO-DAEMON -> conf_dir = /home/kjellgrb/.canto-ng/
16:01:56 : PLUGINS -> [plugin] pushbullet - DISABLED
16:01:56 : SHELF -> Shelf opened: <shelve.DbfilenameShelf object at 0x7f68640307f0>
16:01:56 : CONFIG -> Read /home/kjellgrb/.canto-ng//conf
16:01:56 : CONFIG -> Parsed into: {'CantoCurses': {'browser': {'path': 'lynx'}}, 'feeds': [{'url': 'https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic&os_username=benny&os_password=secret', 'name': 'Jira1'}, {'url': 'https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic', 'password': 'secret', 'user': 'benny', 'name': 'Jira2'}], 'defaults': {'keep_time': 86400, 'keep_unread': False, 'global_transform': 'None', 'rate': 10}}
16:01:56 : CONFIG -> Validated: {'CantoCurses': {'browser': {'path': 'lynx'}}, 'feeds': [{'url': 'https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic&os_username=benny&os_password=secret', 'name': 'Jira1'}, {'url': 'https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic', 'password': 'secret', 'user': 'benny', 'name': 'Jira2'}], 'defaults': {'keep_time': 86400, 'keep_unread': False, 'rate': 10, 'global_transform': 'None'}}
16:01:56 : CANTO-DAEMON -> Listening on unix socket: /home/kjellgrb/.canto-ng//.canto_socket
16:01:56 : SERVER -> Spawned connection monitor thread.
16:01:56 : CANTO-FETCH -> Started thread for feed https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic&os_username=benny&os_password=secret
16:01:56 : FEED -> Fetched previous content for https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic&os_username=benny&os_password=secret.
16:01:56 : FEED -> Item not over keep_time (86400): urn:uuid:51ad59f9-f9c0-3ea4-9c70-517d8d45ec60
16:01:56 : FEED -> Item not over keep_time (86400): urn:uuid:d525cf67-d314-31ab-b1a1-f072cb620920
16:01:56 : FEED -> Item not over keep_time (86400): urn:uuid:e29efeeb-d79d-3532-ad08-3362eca2d4bb
16:01:56 : FEED -> Item not over keep_time (86400): urn:uuid:f5099065-7a90-3478-8f05-59e8996dff6a
16:01:56 : FEED -> Item not over keep_time (86400): urn:uuid:a56ad22a-03cc-3df8-974b-3c43acc68892
16:01:56 : FEED -> Item not over keep_time (86400): urn:uuid:f8db34c4-bf17-37b3-8077-b38ec648a2f4
16:01:56 : FEED -> Item not over keep_time (86400): urn:uuid:c6656fd5-c8e1-35cb-a08b-b903ab041a6d
16:01:56 : FEED -> Item not over keep_time (86400): urn:uuid:a2a2d9c2-f3e1-3a44-b682-01da68c6973c
16:01:56 : FEED -> Item not over keep_time (86400): urn:uuid:3b65cd43-53fd-3fe3-80a2-ccf21eee7ba9
16:01:56 : FEED -> Item not over keep_time (86400): urn:uuid:c6a472c6-2e9d-3ac6-bfe5-23fd2a7570e7
16:01:56 : CANTO-FETCH -> Started thread for feed https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic
16:01:56 : CANTO-DAEMON -> Beginning to serve...
16:01:56 : FEED -> Fetched previous content for https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic.
16:01:56 : CANTO-FETCH -> Started thread for feed https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic&os_username=benny&os_password=secret
16:01:57 : CANTO-FETCH -> Started thread for feed https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic
16:01:57 : CANTO-FETCH -> No content in https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic: <unknown>:2:942: mismatched tag
16:01:59 : CANTO-FETCH -> Parsed https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic&os_username=benny&os_password=secret
16:01:59 : CANTO-FETCH -> Plugins complete.
16:01:59 : FEED -> Fetched previous content for https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic&os_username=benny&os_password=secret.
16:02:00 : SHELF -> Unloaded.
16:02:00 : SHELF -> Synced.
16:02:00 : SHELF -> Successfully trimmed db
16:02:00 : SHELF -> Shelf opened: <shelve.DbfilenameShelf object at 0x7f686213b048>

**Comment by themoken** [comment] 2015-01-08 22:14
Okay, I'm writing a test for this, but it looks like feedparser broke this functionality? Or at least isn't accepting it the way it used to.

**Comment by themoken** [comment] 2015-01-08 22:25
Yep, this is related to feedparser issue #283 (https://code.google.com/p/feedparser/issues/detail?id=283) which has a workaround that works. Fix incoming.

**Comment by themoken** [comment] 2015-01-08 22:41
Okay, this should be fixed in git. Reopen if it's still broken for you.

**Closed by themoken** 2015-01-08 22:41 UTC

**Comment by kjellgren** [comment] 2015-01-12 09:03
````
09:57:57 : CANTO-FETCH -> No content in https://jira.3s.intern/activity?maxResults=10&streams=key+IS+UNIX&providers=issues+thirdparty&os_authType=basic: AbstractBasicAuthHandler does not support the following scheme: 'OAuth'

**Comment by themoken** [comment] 2015-01-13 16:42
Hmmm. OAuth is unsupported. When you go to the feed in a browser, does it
open a dialog box to authenticate, or does it forward you to another page
to log in to? If it does forward you and this feed is indeed protected by
OAuth, then I'm afraid this is working as intended.
