### ISSUE TITLE
Corrupted feeds file

### ISSUE THREAD

**Issue by Narrat** [themoken/canto-next#23] opened 2015-10-24 23:48 UTC
Got this problem two times now. Dunno how I achieved it.
Trying to start canto-curses and all I get is a empty screen.

Checking the daemon log provides the following:

>02:42:43 : SHELF -> Failed to JSON load, old shelf?
02:42:43 : SHELF -> Failed to migrate old shelf: db type could not be determined
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/canto_next/storage.py", line 48, in open
    self.cache = json.load(fp)
  File "/usr/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/gzip.py", line 461, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.5/gzip.py", line 409, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'f\xec')

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/usr/bin/canto-daemon", line 7, in <module>
    c = CantoBackend()
  File "/usr/lib/python3.5/site-packages/canto_next/canto_backend.py", line 123, in __init__
    self.get_storage()
  File "/usr/lib/python3.5/site-packages/canto_next/canto_backend.py", line 796, in get_storage
    self.shelf = CantoShelf(self.feed_path)
  File "/usr/lib/python3.5/site-packages/canto_next/storage.py", line 27, in __init__
    self.open()
  File "/usr/lib/python3.5/site-packages/canto_next/feed.py", line 102, in _fl
    return fn(*args)
  File "/usr/lib/python3.5/site-packages/canto_next/storage.py", line 53, in open
    s = shelve.open(self.filename, "r")
  File "/usr/lib/python3.5/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.5/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.5/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined

Removing feeds file makes canto responsive again. But still the question how it could end like this

**Comment by themoken** [comment] 2015-10-29 23:13
Well, corruption could happen if your daemon was killed unexpectedly, like if your machine lost power. I've also had reports of this happening under Upstart when it was failing to actually send SIGTERM on shutdown/restart so the daemon didn't know to stop running and probably died mid-write.

Not sure if there's anything I can do to stop this, but I guess I could make the daemon more resistant by keeping a fallback copy of the feeds file or something if this becomes a chronic issue but I've never seen the daemon corrupt the database during a controlled shutdown.

If you eventually see a pattern that's reproducible, like it occurs after reboot, or something that would be interesting. Would also be interested to know if your using any of the sync plugins.

**Comment by Narrat** [comment] 2015-10-30 08:58
Well it is using systemd as init system and I'm using the user service file. But the machine didn't had lost power unexpectedly, else I wouldn't have opened this issue. Just power on and poweroff. Weird is also, that it happens on my desktop, but not on the laptop,with the same setup.
Will try to get more infos (And I hope a weird running clock cannot be the issue :D )

The only plugin I'm using is cleantitle, so no one of the sync plugins

**Comment by Narrat** [comment] 2015-11-07 02:51
Lovely. If something shall happen it won't.
But another question. What happens if I issued shutdown while canto is trying to retrieve feeds?

**Comment by themoken** [comment] 2015-11-07 22:16
If you shutdown, the daemon should receive a signal (SIGTERM) from your init system which invokes a signal handler that calls cleanup() and then sys.exit(). The very first thing cleanup() does is stop_feeds() which sets marks every Feed object as "stopped".

Any threads currently fetching data will finish grabbing data from the internet but see that the feed is stopped and discard the new data before dying without touching the disk (top of Feed.index).

Any threads working on indexing that data (i.e. already got data and started to parse it while the feed was live) will finish parsing but see that they're stopped without touching the disk (bottom of Feed.index)

Back in the main thread, cleanup() waits for all of the feed threads to finish by locking all of them, this ensures that no threads are still in that small window where it was currently writing to the disk when the feed was stopped because the fetch threads hold these locks until they're 100% complete. After the main threads holds all of these locks, is syncs() and closes() the database and anything else trying to use it will error.

I'm pretty sure that this part of the daemon is solid and a controlled shutdown isn't the source of the corruption.

**Comment by Narrat** [comment] 2015-11-08 12:20
Good to hear. But I somehow achieve this. It happened again, no unusual poweroff and totally clueless.

If internet connection goes down before the daemon is also covered? (in the shutdown process?)

**Comment by themoken** [comment] 2015-11-08 18:14
That should be handled in the same way losing internet is always handled, the fetch thread gets an exception and exits.

Some questions:

1. Since you're asking about shutdown, is it only on the first run on your desktop? i.e. have you determined it *is* shutdown that's causing it?

2. Are you running an experimental FS?

3. Is your disk ancient?

4. Before you remove the feeds file because it's corrupted, what's actually *in* it? Is it empty? If not, try to `cat` and `zcat` it and see if you get anything interesting.

Another idea:

1. Stop using the systemd init file so that canto-curses will start the daemon itself if it's not running. 

2. Then use your shell rc to do something like

    `alias canto-curses="rm -r ~/.config/canto.bak; cp -r ~/.config/canto{,.bak}; canto-curses"`

    (assuming your config is in .config and not .canto-ng, change if necessary)

3. Then, next time this problem occurs you'll have the old daemon-log and be able to see if it has errors, or if it wasn't shutdown correctly, etc.

**Comment by Narrat** [comment] 2015-11-10 10:40
Shutdown could also be a wrong assumption. (And I got a corrupted feed file on another system too)
Just guessing/pointing to shutdown because Before-Shutdown canto is working and after-boot, when die daemon should be started and start canto-curses it hangs, and daemon is failing because of the corrupted file.
It doesn't happen regulary. Just now an then (like 3 times now in dunno. 10-20 boot ups?). So I thought about some race condition that could eventually happen on shutdown.

Both systems are using ext4, but aren't the youngest one. 6-8 years old. Didn't look at the SMART values for quite a while, so maybe there is a problem arising with the disks.

For the last corrupted one I tried to unpack it, but not using zcat and the decompression errored out and left me with an empty file (whereas the compressed one had a size >0 IIRC). Dunno if the archiver got something wrong.

**Comment by Maeda1** [comment] 2015-11-28 09:41
Hi !

Same problem here. It was working good and then, the feed file get empty, resulting in an `canto-curses` hanging.

**Comment by themoken** [comment] 2015-11-29 02:04
Okay guys, I still can't reproduce this but please try on git. I've made three changes.

First, the daemon will march on even if it fails to load the feeds. Not great behavior, but probably better than requiring you to break out rm to get the same effect. This should keep canto-curses from hanging, but if you see a bunch of items come back, the daemon log will say something like

    19:49:45 : SHELF -> Failed to JSON load, old shelf?
    19:49:45 : SHELF -> Failed to migrate old shelf: db type could not be determined
    19:49:45 : SHELF -> BAD DATA: []
    19:49:45 : SHELF -> Carrying on with empty shelf

If you see this, I'm curious what it spits out for BAD DATA (here it's an empty file I made on purpose of course).

Second, I made the daemon dump the file to a tempfile in the same directory and then move it over on sync. This should mean that even if the daemon does get killed in the middle of a sync (for some reason) your old copy of the data should be there (marginally better than corruption). If the machine dies while the move is happening, I'd expect the FS journal to catch that.

Third, I made SIGINT and SIGTERM identical. I did find some bad behavior with getting TERM while threads are running, but even in this case the db was synchronized (some threads were just left hung). I'm not convinced this is the cause of the issue, but it *could* be somehow.

Anyway, grab git and try again.

**Comment by Narrat** [comment] 2015-11-29 11:50
Ok, will do

**Comment by Maeda1** [comment] 2015-12-01 17:43
Before trying the git version, I had one more time this bug.
Then, I post the content of the daemon's log file :
[code]File "/usr/lib/python3.5/dbm/__init__.py", line 88, in open
raise error[0]("db type could not be determined")
dbm.error: db type could not be determined[/code]
I'll try the git version, and report here :)

**Comment by Maeda1** [comment] 2015-12-12 15:00
Hi !

Everything fine since git's installation. Didn't have any corrupted file, or didn't notice.

**Comment by themoken** [comment] 2015-12-15 01:38
Okay, I'll close this. Feel free to reopen if this crops up again.

**Closed by themoken** 2015-12-15 01:38 UTC
